services:
  mysql-container:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: student_pass
    networks:
      - app-network

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb-container:3306/student_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: student_pass
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
