version: '3'
services:
  db:
    image: mysql
    container_name: student-db
    environment:
      MYSQL_ROOT_PASSWORD: student_pass
      MYSQL_DATABASE: student_db
      MYSQL_USER: root
      MYSQL_PASSWORD: student_pass
    ports:
      - "3306:3306"
    networks:
      - student-network
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql  # 可选：初始化数据库

  student-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - student-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/student_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=student_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true

networks:
  student-network:
    driver: bridge
