# Spring Datasource Configuration
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/student_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: root
        password: student_pass
        driver-class-name: com.mysql.cj.jdbc.Driver

    # Spring JPA Configuration
    jpa:
        hibernate:
            ddl-auto: none #根据类文件创建数据表单
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

    sql:
        init:
            mode: always # 启用 SQL 文件自动执行（schema.sql、data.sql）

# Spring Boot Server Configuration
server:
    port: 8080
