# Spring Datasource Configuration
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/student_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
        username: root
        password: student_pass
        driver-class-name: com.mysql.cj.jdbc.Driver

    # Spring JPA Configuration
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect

# Spring Boot Server Configuration
server:
    port: 8080
